# Generated by Django 3.1.2 on 2020-10-24 07:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("S", "Student"),
                    ("T", "Teacher"),
                    ("A", "Admin"),
                    ("M", "Manager"),
                    ("D", "Dean"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
