# Generated by Django 3.1.2 on 2020-10-25 07:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
